/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

//import Shop.*;
import javax.swing.DefaultListModel;

//about of the menubar will have time of each shop.

/**
 *
 * @author ireneah
 */
public class ShoppingGUI extends javax.swing.JFrame {

    /**
     * Creates new form ShoppingGUI
     */
    public ShoppingGUI() {
        initComponents();
    }
    
    String tech[] = {"Camera : $400", "Headphones : $150", "Microphone : $100"};
    String home[] = {"Vase : $70", "Coffee Table : $300", "Chair : $149"};
    String beauty[] = {"Mascara : $25", "Cleanser : $35", "Serum : $249"};
    
    //JList<String> myList = new JList<String>(tech);
    //jListB = new JList(beauty.toArray());
//    DefaultListModel listModel = new DefaultListModel();
//    for (int i = 0; i < tech().size(); i++)
//    {
//        listModel.addElement(tech().get(i));
//    }
//    jListB.setModel(listModel);
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTech = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListT = new javax.swing.JList<>();
        jButtonInfoT = new javax.swing.JButton();
        jLabelItemsT = new javax.swing.JLabel();
        jButtonRateT = new javax.swing.JButton();
        jButtonAddT = new javax.swing.JButton();
        jLabelStore = new javax.swing.JLabel();
        jLabelItemsB = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList<>();
        jButtonTech = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonRate = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonBeauty = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTech = new javax.swing.JMenu();
        jMenuItemAbtTech = new javax.swing.JMenuItem();
        jMenuHome = new javax.swing.JMenu();
        jMenuItemAbtHome = new javax.swing.JMenuItem();
        jMenuBeauty = new javax.swing.JMenu();
        jMenuItemAbtBeauty = new javax.swing.JMenuItem();

        jListT.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListT);

        jButtonInfoT.setText("Get Info");

        jLabelItemsT.setText("Available Items:");

        jButtonRateT.setText("Rate Item");

        jButtonAddT.setText("Add to Cart");

        javax.swing.GroupLayout jPanelTechLayout = new javax.swing.GroupLayout(jPanelTech);
        jPanelTech.setLayout(jPanelTechLayout);
        jPanelTechLayout.setHorizontalGroup(
            jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTechLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddT)
                    .addComponent(jButtonInfoT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTechLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTechLayout.createSequentialGroup()
                            .addGap(289, 289, 289)
                            .addComponent(jButtonRateT))
                        .addComponent(jLabelItemsT))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        jPanelTechLayout.setVerticalGroup(
            jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTechLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTechLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTechLayout.createSequentialGroup()
                        .addComponent(jButtonInfoT)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddT)
                        .addGap(88, 88, 88))))
            .addGroup(jPanelTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTechLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabelItemsT)
                    .addGap(110, 110, 110)
                    .addComponent(jButtonRateT)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelStore.setText("Select a Store:");

        jLabelItemsB.setText("Available Items:");

        jScrollPane2.setViewportView(jListProducts);

        jButtonTech.setText("Techie Tues");
        jButtonTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTechActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add to Cart");

        jButtonRate.setText("Rate Item");

        jButtonHome.setText("DecoratIn'");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonBeauty.setText("Coco smetics");
        jButtonBeauty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeautyActionPerformed(evt);
            }
        });

        jButtonInfo.setText("Get Info");

        jMenuTech.setText("Technology");

        jMenuItemAbtTech.setText("About");
        jMenuItemAbtTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbtTechActionPerformed(evt);
            }
        });
        jMenuTech.add(jMenuItemAbtTech);

        jMenuBar1.add(jMenuTech);

        jMenuHome.setText("Home and Kitchen");

        jMenuItemAbtHome.setText("About");
        jMenuHome.add(jMenuItemAbtHome);

        jMenuBar1.add(jMenuHome);

        jMenuBeauty.setText("Beauty");

        jMenuItemAbtBeauty.setText("About");
        jMenuBeauty.add(jMenuItemAbtBeauty);

        jMenuBar1.add(jMenuBeauty);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonTech)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonHome)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonBeauty))
                    .addComponent(jLabelItemsB)
                    .addComponent(jLabelStore)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonInfo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonInfo, jButtonRate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelStore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTech)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonBeauty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelItemsB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbtTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbtTechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAbtTechActionPerformed

    private void jButtonTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTechActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel DLM = new DefaultListModel();
        DLM.addElement("Camera : $400");
        DLM.addElement("Headphones : $150");
        DLM.addElement("Microphone : $100");
        jListProducts.setModel(DLM);
        
    }//GEN-LAST:event_jButtonTechActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel DLM = new DefaultListModel();
        DLM.addElement("Mascara : $25");
        DLM.addElement("Cleanser : $35");
        DLM.addElement("Serum : $249");
        jListProducts.setModel(DLM);
        
        
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonBeautyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeautyActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel DLM = new DefaultListModel();
        DLM.addElement("Vase : $70");
        DLM.addElement("Coffee Table : $300");
        DLM.addElement("Chair : $149");
        jListProducts.setModel(DLM);
    }//GEN-LAST:event_jButtonBeautyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddT;
    private javax.swing.JButton jButtonBeauty;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonInfoT;
    private javax.swing.JButton jButtonRate;
    private javax.swing.JButton jButtonRateT;
    private javax.swing.JButton jButtonTech;
    private javax.swing.JLabel jLabelItemsB;
    private javax.swing.JLabel jLabelItemsT;
    private javax.swing.JLabel jLabelStore;
    private javax.swing.JList<String> jListProducts;
    private javax.swing.JList<String> jListT;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBeauty;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemAbtBeauty;
    private javax.swing.JMenuItem jMenuItemAbtHome;
    private javax.swing.JMenuItem jMenuItemAbtTech;
    private javax.swing.JMenu jMenuTech;
    private javax.swing.JPanel jPanelTech;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
